services:
  mysql:
    image: mysql
    command: ["mysqld", "--default-authentication-plugin=mysql_native_password"]
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d
      - ./docker/data:/var/lib/mysql
    ports:
      - '3334:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tagether
    cap_add:
      - SYS_NICE

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql:db
    ports:
      - '8888:80'
    depends_on:
      - mysql

  front:
    image: node:20
    user: node
    ports:
      - '3009:3009'
    volumes:
      - .:/front
    working_dir: /front
    entrypoint: 'npm run dev'
