version: '3'

services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports: 
      - '8888:80'

  back:
    build: ./back
    volumes:
      - ./back:/usr/share/nginx/html

  front:
    build: 
      context: ./front
      dockerfile: "Dockerfile-product"
    ports:
      - '3000:3000'
    volumes:
      - ./front:/front
    depends_on:
      - back

  nginx:
    image: nginx
    ports:
      - '8080:80'
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - back
