version: '3'

services:
  front:
    build: ./
    ports:
      - '3000:3000'
    volumes:
      - .:/front

  mysql:
    image: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - ./docker/mysql:/var/lib/mysql
    ports:
      - '3334:3306'
    environment:
      MYSQL_ROOT_PASSWORD: strapi
      MYSQL_DATABASE: tagether
    cap_add:
      - SYS_NICE
