version: '3'

services:
  mysql:
    image: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d
      - ./docker/data:/var/lib/mysql
    ports:
      - '3334:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tagether
    cap_add:
      - SYS_NICE

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql:db
    ports: 
      - '8888:80'
    depends_on: 
      - mysql

  back:
    build: ./back
    volumes:
      - ./back:/usr/share/nginx/html
      - ./back/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - mysql

  front:
    image: node
    ports:
      - '3009:3009'
    volumes:
      - ./front:/front
    environment:
      - PORT=3009
    working_dir: /front
    entrypoint: "npm run dev"
    depends_on:
      - back

  nginx:
    image: nginx
    ports:
      - '8079:80'
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - back
